lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug DiscussWeb.Plugs.SetUser
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", DiscussWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", TopicController, :index)
    resources("/topics/", TopicController)
  end

  scope "/auth", DiscussWeb do
    pipe_through(:browser)

    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end
  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

lib/discuss/application.ex
defmodule Discuss.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Discuss.Repo, []),
      # Start the endpoint when the application starts
      supervisor(DiscussWeb.Endpoint, [])
      # Start your own worker by calling: Discuss.Worker.start_link(arg1, arg2, arg3)
      # worker(Discuss.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss/comment.ex
defmodule Discuss.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Poison.Encoder, only: [:content, :user]}

  schema "comments" do
    field :content, :string
    belongs_to :user, Discuss.User
    belongs_to :topic, Discuss.Topic

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:content])
    |> validate_required([:content])
  end
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/discuss/topic.ex
defmodule Discuss.Topic do
  use Ecto.Schema
  import Ecto.Changeset

  schema "topics" do
    field(:title, :string)
    
    belongs_to :user, Discuss.User
    has_many :comments, Discuss.Comment
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title])
    |> validate_required([:title])
  end
end

lib/discuss/user.ex
defmodule Discuss.User do
  use Ecto.Schema
  import Ecto.Changeset

  @derive {Poison.Encoder, only: [:email]}

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    has_many :topics, Discuss.Topic
    has_many :comments, Discuss.Comment

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end
end

lib/discuss_web/controllers/auth_controller.ex
defmodule DiscussWeb.AuthController do
  use DiscussWeb, :controller
  plug Ueberauth

  alias Discuss.Repo
  alias Discuss.User

  def callback(%{:assigns => %{ueberauth_auth: auth}} = conn, _params) do
    user_params = %{token: auth.credentials.token, email: auth.info.email, provider: "github"}
    changeset = User.changeset(%User{}, user_params)

    signin(conn, changeset)
  end

  def signout(conn, _params) do
    conn
    |> configure_session(drop: true)
    |> redirect(to: topic_path(conn, :index))
  end

  defp signin(conn, changeset) do
    case insert_or_update_user(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> put_session(:user_id, user.id)
        |> redirect(to: topic_path(conn, :index))
      {:error, reason} ->
        IO.inspect reason
        conn
        |> put_flash(:error, "Error Signing in")
        |> redirect(to: topic_path(conn, :index))
    end
  end

  defp insert_or_update_user(changeset) do
    case Repo.get_by(User, email: changeset.changes.email) do
      nil -> 
        Repo.insert(changeset)
      user ->
        {:ok, user}
    end
  end
end

lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller

  alias Discuss.Repo
  alias Discuss.Topic

  plug DiscussWeb.Plugs.RequireAuth when action in [:new, :create, :edit, :update, :delete]
  plug :check_topic_owner when action in [:edit, :update, :delete]
  
  def index(conn, _params) do
    topics = Repo.all(Topic)
    render(conn, "index.html", topics: topics)
  end

  def show(conn, %{"id" => topic_id}) do
    topic = Repo.get!(Topic, topic_id)
    render conn, "show.html", topic: topic
  end

  def new(conn, _params) do
    changeset = Topic.changeset(%Topic{}, %{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"topic" => topic}) do
    changeset = conn.assigns.user
                |> Ecto.build_assoc(:topics)
                |> Topic.changeset(topic)

    case Repo.insert(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Created")
        |> redirect(to: topic_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, %{"id" => topic_id}) do
    topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(topic)

    render(conn, "edit.html", changeset: changeset, topic: topic)
  end

  def update(conn, %{"id" => topic_id, "topic" => topic}) do
    old_topic = Repo.get(Topic, topic_id)
    changeset = Topic.changeset(old_topic, topic)

    case Repo.update(changeset) do
      {:ok, _topic} ->
        conn
        |> put_flash(:info, "Topic Updated")
        |> redirect(to: topic_path(conn, :index))

      {:error, _error_msg} ->
        render(conn, "edit.html", changeset: changeset, topic: old_topic)
    end
  end

  def delete(conn, %{"id" => topic_id}) do
    Repo.get!(Topic, topic_id) |> Repo.delete!()

    conn
    |> put_flash(:info, "Topic Deleted")
    |> redirect(to: topic_path(conn, :index))
  end

  def check_topic_owner(conn, _params) do
    %{params: %{"id" => topic_id}} = conn

    if Repo.get(Topic, topic_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "You cannot edit it")
      |> redirect(to: topic_path(conn, :index))
      |> halt()
    end
  end
end

lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render("500.html", assigns)
  end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"> 
    
    <script>
      <%= if @conn.assigns.user do %>
        window.userToken = "<%= Phoenix.Token.sign(DiscussWeb.Endpoint, "key", @conn.assigns.user.id) %>"
      <% end %>
    </script>

    <style>
    .help-block {
      color: red;
      text-transform: capitalize;
      position: absolute;
      top: 40px;
    }

    .form-group {
      position: relative;
      margin-bottom: 25px;
    }
    </style>
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Discussions
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Sign Out", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/discuss_web/templates/topic/edit.html.eex
<%= form_for @changeset, topic_path(@conn, :update, @topic), fn f -> %>
  <div class="form-group">
    <%= text_input f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

lib/discuss_web/templates/topic/index.html.eex
<h2>Topics</h2>

<ul class="collection">
  <%= for topic <- @topics do %>
    <li class="collection-item">
      <%= link topic.title, to: topic_path(@conn, :show, topic) %>

      <%= if @conn.assigns.user != nil && @conn.assigns.user.id == topic.user_id do %>
        <div class="right">
          <%= link "Edit", to: topic_path(@conn, :edit, topic) %>
          <%= link "Delete", to: topic_path(@conn, :delete, topic), method: :delete %>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

lib/discuss_web/templates/topic/new.html.eex
<%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
  <div class="form-group">
    <%= text_input  f, :title, placeholder: "Title", class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <%= submit "Save Topic", class: "btn btn-primary" %>
<% end %>

lib/discuss_web/templates/topic/show.html.eex
<h5><%= @topic.title %></h5>

<div class="input-field">
  <textarea class="materialize-textarea"></textarea>
  <button class="btn">Add Comment</button>
  <ul class="collection">

  </ul>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    window.createSocket(<%= @topic.id %>)
  });
</script>